// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// cppCalcMOCCS2score
std::unordered_map<std::string, std::vector<std::double_t>> cppCalcMOCCS2score(std::string fileName, std::int32_t klen, bool ignoreLowerCase);
RcppExport SEXP _moccsR_cppCalcMOCCS2score(SEXP fileNameSEXP, SEXP klenSEXP, SEXP ignoreLowerCaseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type fileName(fileNameSEXP);
    Rcpp::traits::input_parameter< std::int32_t >::type klen(klenSEXP);
    Rcpp::traits::input_parameter< bool >::type ignoreLowerCase(ignoreLowerCaseSEXP);
    rcpp_result_gen = Rcpp::wrap(cppCalcMOCCS2score(fileName, klen, ignoreLowerCase));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_moccsR_cppCalcMOCCS2score", (DL_FUNC) &_moccsR_cppCalcMOCCS2score, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_moccsR(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
