# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cppCalcMOCCS2score <- function(fileName, klen, ignoreLowerCase) {
    .Call(`_moccsR_cppCalcMOCCS2score`, fileName, klen, ignoreLowerCase)
}

